server:
  port: 80  #端口
  tomcat:
    uri-encoding: UTF-8   #服务编码
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zcy_forum?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
  data:
    redis:
      # Redis 地址（替换为你的实际IP/端口）
      host: 127.0.0.1
      port: 6379
      # Redis 密码（无密码则注释此行）
      # 数据库索引（默认0）
      database: 0
      # 连接池配置
      lettuce:
        pool:
          # 最大活跃连接数
          max-active: 8
          # 最大空闲连接数
          max-idle: 8
          # 最小空闲连接数
          min-idle: 0
          # 连接等待时间（毫秒）
          max-wait: -1
      # 连接超时时间
      timeout: 5000
  application:
    name: my-spring-ai
  ai:
    dashscope:
      api-key: sk-19b7a926d3fc488383b87efd8ec81f7a
      chat:
        options:
          model: qwen-plus
    openai: #openai配置
      base-url: https://dashscope.aliyuncs.com/compatible-mode #阿里百炼api地址
      #      base-url: https://api.chatanywhere.tech #api地址
      api-key: sk-19b7a926d3fc488383b87efd8ec81f7a #读取环境变量中的阿里百炼 api key
      #      api-key: ${OPENAI_API_KEY} #读取环境变量中的api key
      chat:
        options:
          model: qwen-plus #阿里百炼 模型名称
        enabled: false #关闭OpenAI配置
#          model: gpt-3.5-turbo #模型名称
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG